sudo: required #is required to use docker service in travis

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  
services:
  - docker # required, but travis uses older version of docker :(

script:
  - docker --version
  - make test

after_success:
  - docker --version  # document the version travis is using
